### Register
POST http://localhost:5000/register 
content-type: application/json

{
    "username":"testUser",
    "password": "testPassword",
    "mail": "test@user.com"
}


### Login
POST http://localhost:5000/login 
content-type: application/json

{
    "username":"testUser",
    "password": "testPassword",
    "device":{
        "name":"deviceName",
        "ip": "deviceIp",
        "os": "deviceOs"
    }     
}

### Token
POST http://localhost:5000/token 
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJ1c2VyIjoidGVzdFVzZXIiLCJtYWlsIjoidGVzdEB1c2VyLmNvbSIsImlhdCI6MTU5ODg3OTE3OCwibmJmIjoxNTk4ODc5MTgwLCJleHAiOjE2MDE0NzExNzgsImF1ZCI6Im15YXVkIiwiaXNzIjoibXlpc3N1ZXIiLCJzdWIiOiJ2IiwianRpIjoiMSJ9.FTwtrRoFbN7NrW5joCXFit-eXB8OyXWE_2o9WQZAgSVfbL1jUIy9Xxgg-pUbxMzSmJHLcaXblb8I15xKMd0Xdasv0_OJXO2BdyvTTT0oYzhRbU4Dxh3q7RdPza6g2c8W0-nKwBdJXOKyO01GsbLXBTGZwVuzeZgjL6ljRDd9R65RseAvqAsbaFwSU2wzWtPoaGPEedagabmekF9BX8BbFujVCLQOYHig3yvbeUUrFnw5C-ZfRkh5dSbkS8yDl8Bx3b29elMuMhzfHCX8fCvAI3viGBmZP5rmbVlNG1qlliUW24ZnwSOhD4ixOk48rl1UlbhOkxZcKTQYsbRm7S9aBg"
}

### Invalidate Refresh Token
DELETE http://localhost:5000/token 
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJ1c2VyIjoidGVzdFVzZXIiLCJtYWlsIjoidGVzdEB1c2VyLmNvbSIsImlhdCI6MTU5ODg3OTE3OCwibmJmIjoxNTk4ODc5MTgwLCJleHAiOjE2MDE0NzExNzgsImF1ZCI6Im15YXVkIiwiaXNzIjoibXlpc3N1ZXIiLCJzdWIiOiJ2IiwianRpIjoiMSJ9.FTwtrRoFbN7NrW5joCXFit-eXB8OyXWE_2o9WQZAgSVfbL1jUIy9Xxgg-pUbxMzSmJHLcaXblb8I15xKMd0Xdasv0_OJXO2BdyvTTT0oYzhRbU4Dxh3q7RdPza6g2c8W0-nKwBdJXOKyO01GsbLXBTGZwVuzeZgjL6ljRDd9R65RseAvqAsbaFwSU2wzWtPoaGPEedagabmekF9BX8BbFujVCLQOYHig3yvbeUUrFnw5C-ZfRkh5dSbkS8yDl8Bx3b29elMuMhzfHCX8fCvAI3viGBmZP5rmbVlNG1qlliUW24ZnwSOhD4ixOk48rl1UlbhOkxZcKTQYsbRm7S9aBg"
}

### Private route example
GET http://localhost:5000/private
Cookie: token=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJteWNsYWltIjoic29tZXRoaW5nIiwiaWF0IjoxNTk4ODc4NjQwLCJuYmYiOjE1OTg4Nzg2NDIsImV4cCI6MTU5ODg3OTU0MCwiYXVkIjoibXlhdWQiLCJpc3MiOiJteWlzc3VlciIsInN1YiI6InYiLCJqdGkiOiIxIn0.jsQBs_1CjKt2lM2FW04vuq6PAeGy-_N89015MO_CZaS7EC2Gd1KuCu8p4aAMf6K8d_jteWaAAI8msC-Z0UN7vKFz2Z0lV_HJM_yphLhUNwZhS5cB8xYOVN2P1mGoAKCZxhrpcE_Oeuf2vSTAHUp1oX08Q235DuMMvDdtCMbLhvGxQqZEa3oKryqHfg9V4AfHg-zar0BcaHHXRy7TpGJi3DZVTCPj92VUnwQXDYLy2e145nz-rwP04vOWs2P0m71I1OwMj2nSPKG3TMTLjXdGl8U-7BPG7fGcVP2iu13ps_G9BKj_x9oYLJEautKZT1qae5dbnL_ZhL8Lz0w92VlCMw

### PublicKey
GET http://localhost:5000/publicKey

### KafkaTest
GET http://localhost:5000/kafka