### Register
POST http://localhost:5000/register 
content-type: application/json

{
    "username":"testUser",
    "password": "testPassword",
    "mail": "test@user.com"
}


### Login
POST http://localhost:5000/login 
content-type: application/json

{
    "username":"testUser",
    "password": "testPassword"
}

### Token
POST http://localhost:5000/token 
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJ1c2VyIjoidGVzdFVzZXIiLCJtYWlsIjoidGVzdEB1c2VyLmNvbSIsImlhdCI6MTU5ODc5NjM1MywibmJmIjoxNTk4Nzk2MzU1LCJleHAiOjE2MDEzODgzNTMsImF1ZCI6Im15YXVkIiwiaXNzIjoibXlpc3N1ZXIiLCJzdWIiOiJ2IiwianRpIjoiMSJ9.EPQ3ZsCuwVf11SiL3VcYKx5_R3p8iYJ_N1QqLDZsqZkfbyBjLcxd8UcqpvjTHC8wLb54o6wc-NR-DUyguYP05g"
}

### Private route example
GET http://localhost:5000/private?token=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJteWNsYWltIjoic29tZXRoaW5nIiwiaWF0IjoxNTk4Nzk3MDU0LCJuYmYiOjE1OTg3OTcwNTYsImV4cCI6MTU5ODc5Nzk1NCwiYXVkIjoibXlhdWQiLCJpc3MiOiJteWlzc3VlciIsInN1YiI6InYiLCJqdGkiOiIxIn0.J6VFOTHyh8FGLpN9-AypB262HwKed8RjEGKaPFiIBulDq25jRZcHTKNbw-AoQzNDNUT3eyuCpi1RfwoATAcpjUtHjZsF-u93DUMeBAE4wZbS6jCzpsd0gPF_iHwaAF4q05iD6U2N3QIRPhewu8Gjz8mGEDCiK5VUFl-Q7ckTUh-VF5AS9jq06ICu3-kX0nEcdjRn9svpasr_a-3jw8YMVPrjN09sC-G1jK_OD_Woxqnz_h-XR66IvM6qe5U8W6URS18xIF9ya22VbC6cGZ0jqReHxT2ueA9Atp9OtQhAUhoZLA0dr3nk_qQsV0Wf7lUm0E2U4ehxoc6BEcynFKftAw

content-type: application/json


